package ch.uzh.ifi.Mechanisms;

import ch.uzh.ifi.MechanismDesignPrimitives.Type;
import java.util.List;

public class JoinPlannerFactory implements IPlannerFactory
{
	/*
	 * Constructor.
	 */
	public JoinPlannerFactory(int numberOfBuyers, int numberOfSellers, List<Type> types, boolean isInjectable, int numberOfPlans, int minSellersPerPlan, int maxSellersPerPlan)
	{
		_numberOfBuyers = numberOfBuyers;
		_numberOfSellers = numberOfSellers;
		_types = types;
		_isInjectable = isInjectable;
		_numberOfPlans = numberOfPlans;
		_minSellersPerPlan = minSellersPerPlan;
		_maxSellersPerPlan = maxSellersPerPlan;
	}
	
	/*
	 * (non-Javadoc)
	 * @see Mechanisms.IPlannerFactory#producePlanner()
	 */
	@Override
	public Planner producePlanner() 
	{
		Planner planner = new JoinErrorPlanner(_numberOfBuyers, _numberOfSellers, _types);
		planner.setNumberOfPlans(_numberOfPlans);
		planner.setMinSellersPerPlan(_minSellersPerPlan);
		planner.setMaxSellersPerPlan(_maxSellersPerPlan);
		
		if( _isInjectable )
			planner.makeInjectable();
		else
			planner.makeNonInjectable();
		
		planner.reset(_types);
		planner.generatePlans();
		return planner;
	}
	
	@Override
	public Planner producePlanner(long seed) {
		// TODO Auto-generated method stub
		return null;
	}

	private boolean _isInjectable;									//A flag indicating if an error can be injected into plans
	private List<Type> _types;										//The list of types reported to the planner	

	private int _numberOfBuyers;									//The number of buyers
	private int _numberOfSellers;									//The number of sellers
	
	private int _numberOfPlans;										//The max number of plans can be generated by the planner
	private int _minSellersPerPlan;									//The min number of sellers per plan
	private int _maxSellersPerPlan;									//The max number of sellers per plan
}
